### ISSUE TITLE
Multiple-domains

### ISSUE THREAD

**Issue by NikRimington** [mattou07/iis-builder#1]
Hey Matt,

That's a wickedly cool script. However I've noticed that if you try to bind multiple domains it's not creating multiple certificates but only a single certificate that only covers the first domain you provide in the bindings. Would be great if it could either create a certificate for multiple domains, or multiple certificates, one for each binding :-)

Nik

**Comment by mattou07** [comment]
Could you comment what's in your json file? It will help me replicate the issue if its some odd edge case. 

"Bindings" should look something like this for multiple domains:
 `"bindings": ["test-site.localtest.me","test-site2.local","test-site3.localtest.me"]`

Will attempt to replicate this and get back to you with what I find.

**Comment by NikRimington** [comment]
Hey Matt, no problem:

```
{
    "IIS-Site-Name": "site.local",
    "App-Pool-Name": "site.local",
    "IIS-App-Pool-Dot-Net-Version": "v4.0",
    "bindings": ["site.localtest.me", "site.local"]
}
```

It's strange, it's created the bindings and everything it's just missing the certificate for the second domain and as such uses the certificate for the first domain in the binding.

**Comment by mattou07** [comment]
I think I have discovered the issue I have the fix sitting on another branch, can you let me know if it resolves your issue and I will merge it in: https://github.com/mattou07/iis-builder/pull/2

In the meantime I will just make sure it still works for the other projects it is used on. Thanks for discovering this!!

**Comment by NikRimington** [comment]
Looks like that PR change does fix the issue :-) Nice one!

**Comment by mattou07** [comment]
Cool merged, thanks again!
