### ISSUE TITLE
Re-running the script doesn't add new certs/bindings

### ISSUE THREAD

**Issue by NikRimington** [mattou07/iis-builder#4]
I tried adding a new domain binding into the config file and re-running the builder script.

**What I expected** was that a new cert for the new binding would be created and a new binding created in IIS.

**What happened** was that nothing happened. No messages/errors, nothing. 

Is it possible to amend the IIS script to add/remove bindings and certs if the config is updated?

**Comment by mattou07** [comment]
Just for clarification, is this for an IIS site that already exists / already been created previously?

**Comment by NikRimington** [comment]
Yep, exactly that. Currently the work around is to delete the site from IIS then run the script again, but that seems a bit unnecessary.

**Comment by mattou07** [comment]
Cool, will take a look and get back to you with a PR, thanks for using the script 😄 !

**Comment by mattou07** [comment]
Hey @NikRimington , you can checkout the fix for this here: https://github.com/mattou07/iis-builder/pull/5

It will remove the site if it already exists and add the new bindings when creating the site again.

If this is not ideal please let me know.

Again thanks for using the script!

**Comment by mattou07** [comment]
Pull Requested Merged Closing Issue. Thanks for reporting this!
