### ISSUE TITLE
Copy certificates into a folder

### ISSUE THREAD

**Issue by Sibren** [mattou07/iis-builder#9]
Hi,

This might be a basic question, but I couldn't find the answer online..
What I would like, is after creating the IIS-project and the SSL-certificate, I would like to copy the .crt and the .key into a relative folder.
So, when running the ps-script, I would like to create an SSL-folder in my project with the .crt and the .key.

Is this doable?

**Comment by mattou07** [comment]
I think you are looking to create a .pfx file. I assume you want to export the certificate into a file and then apply it to another machine? If my assumption is correct then sure creating a pfx shouldn't be too complicated.

**Comment by mattou07** [comment]
Haven't had a response so I am closing this issue. Thanks for using the script!
